### ISSUE TITLE
Issue with the py

### ISSUE THREAD

**Issue by 0xYpY** [Minh-Trng/dex-buy-tools#6]
Hi !
When i run a command i get this error :

```
root@dex-tools:~/dex# dexbuy instant bsc 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
Traceback (most recent call last):
  File "/usr/local/bin/dexbuy", line 5, in <module>
    from dexbuytools.__main__ import dexbuy
  File "/usr/local/lib/python3.10/site-packages/dexbuytools/__main__.py", line 38, in <module>
    def onliquidity(network_name, token_address, search_term, buy_params_path, wallet_data_path, general_params_path):
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2465, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2029, in __init__
    self.name, self.opts, self.secondary_opts = self._parse_decls(
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2610, in _parse_decls
    raise TypeError(
TypeError: No options defined but a name was passed (search_term). Did you mean to declare an argument instead? Did you mean to pass '--search_term'?
```
I run on docker python:latest (debian11)

root@dex-tools:~/dex# python --version
Python 3.10.4

Could you help me ?

regards

**Comment by Minh-Trng** [comment]
Hey, this is indeed a bug. the program is ttying to execute the "onliquidity" option instead of "instant" will try to resolve it and let you know

**Comment by Minh-Trng** [comment]
was a minor mistake in the naming convention of options, should be working now :)

**Comment by 0xYpY** [comment]
Yeah thx, I will check that !

I have a little request, can you add cronos nativly 

some help :

```
CRO_RPC_URL: https://evm.cronos.org/
ROUTER_ABI_MMF : 0x145677FC4d9b8F19B5D56d1820c48e0443049a30 
MAIN_TOKEN_ADDRESS : 0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23
```

**Comment by Minh-Trng** [comment]
thanks, that was useful info to get started :)

I have added an implementation for it. Brownie does not support cronos-forking, so I have not written any tests for it. 

Can you set up a burner wallet with a tiny amount of funds and test it?

**Comment by 0xYpY** [comment]
In fact, I copy BSC files (helpers/BscHelper.py ...) and adapt to cronos and instant buy work well.

I dont realy kwno how set a burner wallet...

**Comment by Minh-Trng** [comment]
burner wallet just means a new wallet that you dont use for anything else

**Comment by Minh-Trng** [comment]
but if it works for you now, feel free to close the issue :)

**Comment by 0xYpY** [comment]
thx a lot
