### ISSUE TITLE
401 Client Error: Unauthorized for url: https://mainnet.infura.io/v3/...

### ISSUE THREAD

**Issue by fabston** [Minh-Trng/dex-buy-tools#7]
Hi there,

I already updated `dexbuytools/config/general_params.yml` file with my infura project id but I keep getting:

`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://mainnet.infura.io/v3/...`

Do you have an idea why that is happening? Appreciate your help.

**Comment by Minh-Trng** [comment]
Hi,
that should mean your id is invalid, have you used it somewhere else?
also, what was the exact command you were using in the terminal?

**Comment by fabston** [comment]
I created a new infura id just for this project... 

The command I was using is `dexbuy instant eth 0x...`

Folder structure:
```
|- dexbuytools
|-- config
|--- buy_params.yml
|--- general_params.yml
|--- wallet_data.yml
```

I also btw tried an Alchemy RPC, but did not work either, same error

**Comment by fabston** [comment]
Ok, so it seems the `general_param` are being taken from `/lib/python3.8/site-packages/dexbuytools/config/general_params.yml`...

Any idea why it takes it from the venv?

Apart from that I also tried `onliquidity` using the command:

`dexbuy onliquidity eth --token_address 0xac4b3dacb91461209ae9d41ec517c2b9cb1b7daf`

but that returns `Error: No such option: --token_address`.

**Comment by Minh-Trng** [comment]
thank you for digging a bit deeper into the problem, thats a very useful hint 👍 
I will check how to fix the search path for config

regarding the onliquidity command: I think I had this bug on the radar, but ended up forgetting about this, because I havent used it so far. Will check this out too asap

**Comment by fabston** [comment]
Awesome, thanks for looking into that.

Another idea I had for onliquidity is to pass an option to wait X amount of blocks until swapping. Nowadays the common practice is to wait at least 3 blocks after the confirmation otherwise you are it risk of getting blacklisted.

**Comment by Minh-Trng** [comment]
try using "_pip install --editable ._". 

the editable-flag does not pack the source code separately and should use the right config then. I have tried it on a windows device and it worked for me (but I dont think it should be any different for Linux)

Since you are testing it on the eth network, a small note: the current implementation uses the flashbots network and does not send to the mainnet directly. This means that there is no guarantee that your tx goes through, but on the bright side you dont pay any gas for those tx that get not included.

**Comment by fabston** [comment]
That worked, thank you!

I am aware of it using flashbots and I think thats great. Does that also improve the possibility of getting filled or the main advantage is that you dont get charged for gas with tx that get not included.

**Comment by Minh-Trng** [comment]
> That worked, thank you!
> 
> I am aware of it using flashbots and I think thats great. Does that also improve the possibility of getting filled or the main advantage is that you dont get charged for gas with tx that get not included.

I am not sure about that tbh. I think 90% of miners use flashbots, so I thought odds should be higher, but in my experience probably less than 50% of my txs go through on Ethereum. But this again could be because I am only sending bundles to flash bots for 3 blocks (as seen [here](https://github.com/Minh-Trng/dex-buy-tools/blob/master/dexbuytools/helpers/EthHelper.py) in lin 112) in order to avoid buying late when the price has spiked a lot. Should be made configurable instead of hardcoding it

**Comment by fabston** [comment]
I see, makes sense yea. How could I increase the possibility of getting filled in coins with just added liquidity (regardless of big spikes).

**Comment by Minh-Trng** [comment]
Increasing the bribe that is send to the Flashbots network should help. Also increasing the amount of blocks for which bundles are sent could help if your transaction did not get included in the first ones

**Comment by Minh-Trng** [comment]
but the flashbots network is kind of a blackbox afaik, so knowing exactly why your tx did not get in is a bit difficult

**Comment by fabston** [comment]
I see. So I guess changing line #111 to `for i in range(1, 3)` to `for i in range(1, 6):` and bribe to maybe `0.1`?

Also I cant really know by the terminal response if the swap succeeded or not right? I'd have to check etherscan. Correct?

**Comment by Minh-Trng** [comment]
> I see. So I guess changing line #111 to `for i in range(1, 3)` to `for i in range(1, 6):` and bribe to maybe `0.1`?
> 
> Also I cant really know by the terminal response if the swap succeeded or not right? I'd have to check etherscan. Correct?

0.1 ETH bribe seems a bit over the top, I think you just need to check the average of recent successful bribes and go with something slightly above. On the flashbots website there is a statistic iirc.

and yes, you need to check on etherscan if there is a transaction, dexbuytools will just tell you that a bundle was sent to the flashbots network

**Comment by Minh-Trng** [comment]
> Apart from that I also tried `onliquidity` using the command:
> 
> `dexbuy onliquidity eth --token_address 0xac4b3dacb91461209ae9d41ec517c2b9cb1b7daf`
> 
> but that returns `Error: No such option: --token_address`.

this seems to work fine for me btw (havent performed an actual buy, but it doesn't throw an exception at least)

**Comment by fabston** [comment]
> > Apart from that I also tried `onliquidity` using the command:
> > `dexbuy onliquidity eth --token_address 0xac4b3dacb91461209ae9d41ec517c2b9cb1b7daf`
> > but that returns `Error: No such option: --token_address`.
> 
> this seems to work fine for me btw (havent performed an actual buy, but it doesn't throw an exception at least)

Ok, I will test it myself again. Might've also been due to the falsely pip install from me. Will report back.

**Comment by fabston** [comment]
One thing I have noticed but not sure. I increased the range to `6` but I got filled twice, is that normal?

**Comment by Minh-Trng** [comment]
> One thing I have noticed but not sure. I increased the range to `6` but I got filled twice, is that normal?

no this is definitely not supposed to happen, you sure you bought double the amount of tokens? etherscan will show you 2 txs, but one of them is just the bribe

**Comment by fabston** [comment]
> > One thing I have noticed but not sure. I increased the range to `6` but I got filled twice, is that normal?
> 
> no this is definitely not supposed to happen, you sure you bought double the amount of tokens? etherscan will show you 2 txs, but one of them is just the bribe

Yea I’m aware to see 2 tx but in my example I had 4. I might’ve ran the command too frequently since the first 1/2 did not succeed.

**Comment by fabston** [comment]
Would there be a way to not use flashbots? Because I keep having quite some issues with it, also given that I can never really tell what has happened in the tx. If it succeeded etc.

**Comment by Minh-Trng** [comment]
> Would there be a way to not use flashbots? Because I keep having quite some issues with it, also given that I can never really tell what has happened in the tx. If it succeeded etc.

not in a configurable way as of now, but if you need it urgently just replace the method body of buy_instantly(...) in EthHelper.py with the same body as all other helpers: 

`return super().perform_uniswapv2_style_buy(token_address)`
